name: Build PHP7

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, json, grpc, protobuf

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            ./php7/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/php7/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          cd php7
          composer install --prefer-dist --no-progress

      - name: Install Specific Protoc Version
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip
          unzip protoc-27.1-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/* /usr/local/bin/
          sudo mv protoc/include/* /usr/local/include/

      - name: Check Protoc Version
        run: |
          protoc --version

      - name: Cache gRPC PHP plugin
        uses: actions/cache@v3
        id: cache-grpc-php-plugin
        with:
          path: |
            ./grpc/cmake/build
          key: ${{ runner.os }}-grpc-php-plugin-v1.64.2

      - name: Build gRPC PHP plugin
        if: steps.cache-grpc-php-plugin.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y build-essential autoconf libtool pkg-config
          git clone --recurse-submodules -b v1.64.2  https://github.com/grpc/grpc
          cd grpc
          mkdir -p cmake/build
          cd cmake/build
          cmake ../..
          make grpc_php_plugin

      - name: Install gRPC PHP plugin
        run: |
          sudo cp ./grpc/cmake/build/grpc_php_plugin /usr/local/bin/

      - name: Compile Protobuf file
        run: |
          mkdir -p php7/output
          protoc --proto_path=src/main/proto --php_out=./php7/output --grpc_out=./php7/output --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin src/main/proto/com/kodypay/grpc/pay/v1/pay.proto

      - name: Package the compiled files
        run: |
          cd php7/output
          zip -r kody-php7-grpc-package.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kody-php7-grpc-package
          path: ./php7/output/kody-php7-grpc-package.zip
